namespace CreatioHelper.Application.Interfaces;

/// <summary>
/// Repository for sync event log persistence - compatible with Syncthing's event system
/// </summary>
public interface IEventLogRepository : IDisposable
{
    /// <summary>
    /// Save an event to the log
    /// </summary>
    Task SaveEventAsync(EventLogEntry entry);

    /// <summary>
    /// Save multiple events to the log
    /// </summary>
    Task SaveEventsAsync(IEnumerable<EventLogEntry> entries);

    /// <summary>
    /// Get events since a specific event ID
    /// </summary>
    Task<IReadOnlyList<EventLogEntry>> GetEventsSinceAsync(long sinceId, int limit = 100, string[]? eventTypes = null);

    /// <summary>
    /// Get the last event ID
    /// </summary>
    Task<long> GetLastEventIdAsync();

    /// <summary>
    /// Delete events older than the specified time
    /// </summary>
    Task<int> DeleteEventsOlderThanAsync(DateTime cutoff);

    /// <summary>
    /// Get event count
    /// </summary>
    Task<long> GetEventCountAsync();
}

/// <summary>
/// Represents a sync event log entry for persistence
/// </summary>
public class EventLogEntry
{
    /// <summary>
    /// Unique event ID (auto-generated by database)
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Global timestamp for when the event occurred
    /// </summary>
    public DateTime GlobalId { get; set; }

    /// <summary>
    /// Event type name
    /// </summary>
    public string EventType { get; set; } = string.Empty;

    /// <summary>
    /// Event timestamp
    /// </summary>
    public DateTime EventTime { get; set; }

    /// <summary>
    /// JSON-serialized event data
    /// </summary>
    public string Data { get; set; } = "{}";

    /// <summary>
    /// When the entry was created in the database
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
