global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using System.Text.Json;
global using CreatioHelper.Application.Interfaces;
global using CreatioHelper.Agent.Extensions;
global using CreatioHelper.Application.Extensions;
global using CreatioHelper.Infrastructure.Extensions;