using System.IO;
using System.Linq;
using CreatioHelper.Infrastructure.Services.Workspace;
using Xunit;

namespace CreatioHelper.UnitTests;

public class SourceSyntaxValidatorTests
{
    private static string CreateDir()
    {
        var dir = Path.Combine(Path.GetTempPath(), "syntax_" + Path.GetRandomFileName());
        Directory.CreateDirectory(dir);
        return dir;
    }

    private static string WriteFile(string dir, string relativePath, string content)
    {
        var full = Path.Combine(dir, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
        return full;
    }

    [Fact]
    public void Validate_ReportsNothing_ForSourcesThatParse()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Schemas\UsrGood\UsrGood.cs",
            "namespace Terrasoft.Configuration\n{\n    public class UsrGood\n    {\n        public string Name { get; set; }\n    }\n}\n");
        WriteFile(dir, @"UsrPkg\Schemas\UsrGood\UsrGood.js",
            "define(\"UsrGood\", [\"ext-base\"], function(Ext) {\n    return { attributes: {} };\n});\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        Assert.Empty(errors);
    }

    [Fact]
    public void Validate_ReportsTheFileAndLine_ForBrokenCSharp()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Schemas\UsrBroken\UsrBroken.cs",
            "namespace Terrasoft.Configuration\n{\n    public class UsrBroken\n    {\n        public void Run()\n        {\n            var x = 1;\n    }\n}\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        var error = Assert.Single(errors);
        Assert.Contains("UsrBroken.cs", error);
        Assert.Contains("CS1513", error);
    }

    [Fact]
    public void Validate_ReportsBrokenJavaScript()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Schemas\UsrBroken\UsrBroken.js",
            "define(\"UsrBroken\", [], function() {\n    return { a: { , } };\n});\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        var error = Assert.Single(errors);
        Assert.Contains("UsrBroken.js", error);
    }

    [Fact]
    public void Validate_AcceptsEsModules()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Schemas\UsrModule\UsrModule.js",
            "import { thing } from \"./thing.js\";\nexport const value = thing;\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        Assert.Empty(errors);
    }

    [Fact]
    public void Validate_SkipsGeneratedAndVendorDirectories()
    {
        var dir = CreateDir();
        var broken = "class { { {\n";
        WriteFile(dir, @"UsrPkg\Files\node_modules\lib\broken.cs", broken);
        WriteFile(dir, @"UsrPkg\Files\obj\broken.cs", broken);
        WriteFile(dir, @"UsrPkg\Files\bin\broken.cs", broken);

        var errors = new SourceSyntaxValidator().Validate(dir);

        Assert.Empty(errors);
    }

    [Fact]
    public void Validate_SkipsMinifiedAndBundledJavaScript()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Schemas\UsrVendor\vendor.min.js", "this is ( not javascript ]]]\n");
        WriteFile(dir, @"UsrPkg\Schemas\UsrVendor\1011.hash=28e36a68a77cfe55.js", "this is ( not javascript ]]]\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        Assert.Empty(errors);
    }

    [Fact]
    public void Validate_SkipsAStyleSchemaStoredWithAJsExtension()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Schemas\UsrPageCSS\UsrPageCSS.less",
            "crt-image-input { width: 100%; }\n");
        WriteFile(dir, @"UsrPkg\Schemas\UsrPageCSS\UsrPageCSS.js",
            "[data-item-marker=Image] {\n    width: 100% !important;\n}\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        Assert.Empty(errors);
    }

    [Fact]
    public void Validate_DoesNotParseJavaScriptOutsideSchemas()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Files\src\bundle.js", "function broken( {\n");
        WriteFile(dir, @"UsrPkg\Autogenerated\Src\Manifest.UsrPkg.js", "{\n    \"SyncOptions\": {}\n}\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        Assert.Empty(errors);
    }

    [Fact]
    public void Validate_ReportsEveryBrokenFile()
    {
        var dir = CreateDir();
        WriteFile(dir, @"UsrPkg\Schemas\A\A.cs", "class A { ");
        WriteFile(dir, @"UsrPkg\Schemas\B\B.cs", "class B { ");
        WriteFile(dir, @"UsrPkg\Schemas\C\C.js", "function c( {\n");

        var errors = new SourceSyntaxValidator().Validate(dir);

        Assert.Equal(3, errors.Count);
    }
}
